package com.vakit.widget.domain.location

import java.time.ZoneId

/**
 * Maps the Diyanet country names (Turkish spelling, as returned by the API)
 * to the primary IANA timezone of that country.
 *
 * Prayer times are location-specific and the API does not return a timezone.
 * Without this mapping the countdown could be wrong when the phone is in a
 * different timezone than the selected city. Countries with multiple timezones
 * use their primary/most populous zone. Unknown countries fall back to the
 * device timezone.
 */
object CountryTimeZones {

    private val map = mapOf(
        "TÜRKİYE" to "Europe/Istanbul",
        "KUZEY KIBRIS" to "Asia/Nicosia",
        "ALMANYA" to "Europe/Berlin",
        "AVUSTURYA" to "Europe/Vienna",
        "BELCIKA" to "Europe/Brussels",
        "HOLLANDA" to "Europe/Amsterdam",
        "FRANSA" to "Europe/Paris",
        "INGILTERE" to "Europe/London",
        "ISPANYA" to "Europe/Madrid",
        "ITALYA" to "Europe/Rome",
        "ISVICRE" to "Europe/Zurich",
        "PORTEKIZ" to "Europe/Lisbon",
        "DANIMARKA" to "Europe/Copenhagen",
        "ISVEC" to "Europe/Stockholm",
        "NORVEC" to "Europe/Oslo",
        "FINLANDIYA" to "Europe/Helsinki",
        "IZLANDA" to "Atlantic/Reykjavik",
        "IRLANDA" to "Europe/Dublin",
        "YUNANISTAN" to "Europe/Athens",
        "POLONYA" to "Europe/Warsaw",
        "CEK CUMHURIYETI" to "Europe/Prague",
        "SLOVAKYA" to "Europe/Bratislava",
        "MACARISTAN" to "Europe/Budapest",
        "ROMANYA" to "Europe/Bucharest",
        "BULGARISTAN" to "Europe/Sofia",
        "SIRBISTAN" to "Europe/Belgrade",
        "HIRVATISTAN" to "Europe/Zagreb",
        "SLOVENYA" to "Europe/Ljubljana",
        "LITVANYA" to "Europe/Vilnius",
        "LETONYA" to "Europe/Riga",
        "ESTONYA" to "Europe/Tallinn",
        "UKRAYNA" to "Europe/Kyiv",
        "UKRAYNA-KIRIM" to "Europe/Simferopol",
        "BELARUS" to "Europe/Minsk",
        "RUSYA" to "Europe/Moscow",
        "ARNAVUTLUK" to "Europe/Tirane",
        "BOSNA HERSEK" to "Europe/Sarajevo",
        "KARADAG" to "Europe/Podgorica",
        "MAKEDONYA" to "Europe/Skopje",
        "KOSOVA" to "Europe/Belgrade",
        "MALTA" to "Europe/Malta",
        "LUKSEMBURG" to "Europe/Luxembourg",
        "MONAKO" to "Europe/Monaco",
        "LIECHTENSTEIN" to "Europe/Vaduz",
        "ANDORRA" to "Europe/Andorra",
        "SAN MARINO" to "Europe/San_Marino",
        "VATIKAN" to "Europe/Vatican",
        "GIBRALTAR" to "Europe/Gibraltar",
        "AZERBAYCAN" to "Asia/Baku",
        "GURCISTAN" to "Asia/Tbilisi",
        "ERMENISTAN" to "Asia/Yerevan",
        "IRAN" to "Asia/Tehran",
        "IRAK" to "Asia/Baghdad",
        "SURIYE" to "Asia/Damascus",
        "URDUN" to "Asia/Amman",
        "LUBNAN" to "Asia/Beirut",
        "ISRAIL" to "Asia/Jerusalem",
        "FILISTIN" to "Asia/Gaza",
        "S. ARABISTAN" to "Asia/Riyadh",
        "KUVEYT" to "Asia/Kuwait",
        "BAHREYN" to "Asia/Bahrain",
        "KATAR" to "Asia/Qatar",
        "BIRLESIK ARAP EMIRLIGI" to "Asia/Dubai",
        "UMMAN" to "Asia/Muscat",
        "YEMEN" to "Asia/Aden",
        "AFGANISTAN" to "Asia/Kabul",
        "PAKISTAN" to "Asia/Karachi",
        "HINDISTAN" to "Asia/Kolkata",
        "BANGLADES" to "Asia/Dhaka",
        "SRI LANKA" to "Asia/Colombo",
        "NEPAL" to "Asia/Kathmandu",
        "MALDIVLER" to "Indian/Maldives",
        "KAZAKISTAN" to "Asia/Almaty",
        "OZBEKISTAN" to "Asia/Tashkent",
        "TURKMENISTAN" to "Asia/Ashgabat",
        "KIRGIZISTAN" to "Asia/Bishkek",
        "TACIKISTAN" to "Asia/Dushanbe",
        "MOOGOLISTAN" to "Asia/Ulaanbaatar",
        "CIN" to "Asia/Shanghai",
        "HONG KONG" to "Asia/Hong_Kong",
        "MAKAO" to "Asia/Macau",
        "TAYVAN" to "Asia/Taipei",
        "JAPONYA" to "Asia/Tokyo",
        "GUNEY KORE" to "Asia/Seoul",
        "KUZEY KORE" to "Asia/Pyongyang",
        "TAYLAND" to "Asia/Bangkok",
        "VIETNAM" to "Asia/Ho_Chi_Minh",
        "KAMBOCYA" to "Asia/Phnom_Penh",
        "MALEZYA" to "Asia/Kuala_Lumpur",
        "SINGAPUR" to "Asia/Singapore",
        "ENDONEZYA" to "Asia/Jakarta",
        "FILIPINLER" to "Asia/Manila",
        "MYANMAR" to "Asia/Yangon",
        "BURMA (MYANMAR)" to "Asia/Yangon",
        "BRUNEI" to "Asia/Brunei",
        "DOGU TIMOR" to "Asia/Dili",
        "MISIR" to "Africa/Cairo",
        "FAS" to "Africa/Casablanca",
        "CEZAYIR" to "Africa/Algiers",
        "TUNUS" to "Africa/Tunis",
        "LIBYA" to "Africa/Tripoli",
        "SUDAN" to "Africa/Khartoum",
        "SOMALI" to "Africa/Mogadishu",
        "ETYOPYA" to "Africa/Addis_Ababa",
        "ERITRE" to "Africa/Asmara",
        "CIBUTI" to "Africa/Djibouti",
        "KENYA" to "Africa/Nairobi",
        "TANZANYA" to "Africa/Dar_es_Salaam",
        "UGANDA" to "Africa/Kampala",
        "RUANDA" to "Africa/Kigali",
        "BURUNDI" to "Africa/Bujumbura",
        "KONGO" to "Africa/Kinshasa",
        "DEMOKRATIK KONGO CUMHURIYETI" to "Africa/Kinshasa",
        "NİJERYA" to "Africa/Lagos",
        "NIJERYA" to "Africa/Lagos",
        "GANA" to "Africa/Accra",
        "FILDISI SAHILI" to "Africa/Abidjan",
        "SENEGAL" to "Africa/Dakar",
        "MALI" to "Africa/Bamako",
        "MORITANYA" to "Africa/Nouakchott",
        "FAS (MOROCCO)" to "Africa/Casablanca",
        "GUNEY AFRIKA" to "Africa/Johannesburg",
        "GUNEY AFRİKA" to "Africa/Johannesburg",
        "NAMIBYA" to "Africa/Windhoek",
        "BOTSVANA" to "Africa/Gaborone",
        "ZIMBABVE" to "Africa/Harare",
        "ZAMBIYA" to "Africa/Lusaka",
        "MALAVI" to "Africa/Blantyre",
        "MOZAMBIK" to "Africa/Maputo",
        "ANGOLA" to "Africa/Luanda",
        "ORTA AFRIKA CUMHURIYETI" to "Africa/Bangui",
        "CAD" to "Africa/Ndjamena",
        "KAMERUN" to "Africa/Douala",
        "GABON" to "Africa/Libreville",
        "EKVATOR GINESI" to "Africa/Malabo",
        "GINE" to "Africa/Conakry",
        "SIERRA LEONE" to "Africa/Freetown",
        "LIBERYA" to "Africa/Monrovia",
        "BURKINA FASO" to "Africa/Ouagadougou",
        "NİJER" to "Africa/Niamey",
        "NIJER" to "Africa/Niamey",
        "TOGO" to "Africa/Lome",
        "BENIN" to "Africa/Porto-Novo",
        "SVAZILAND" to "Africa/Mbabane",
        "LESOTO" to "Africa/Maseru",
        "SEYSEL ADALARI" to "Indian/Mahe",
        "MAURITIUS ADASI" to "Indian/Mauritius",
        "MADAGASKAR" to "Indian/Antananarivo",
        "KOMORLAR" to "Indian/Comoro",
        "REUNION" to "Indian/Reunion",
        "KANADA" to "America/Toronto",
        "ABD" to "America/New_York",
        "MEKSIKA" to "America/Mexico_City",
        "BREZILYA" to "America/Sao_Paulo",
        "ARJANTIN" to "America/Argentina/Buenos_Aires",
        "SILI" to "America/Santiago",
        "PERU" to "America/Lima",
        "KOLOMBIYA" to "America/Bogota",
        "VENEZUELA" to "America/Caracas",
        "EKVATOR" to "America/Guayaquil",
        "BOLIVYA" to "America/La_Paz",
        "PARAGUAY" to "America/Asuncion",
        "URUGUAY" to "America/Montevideo",
        "GUYANA" to "America/Guyana",
        "SURINAM" to "America/Paramaribo",
        "GREENLAND" to "America/Godthab",
        "GRONLAND" to "America/Nuuk",
        "KUDUS" to "Asia/Jerusalem",
        "YENI ZELLANDA" to "Pacific/Auckland",
        "AVUSTRALYA" to "Australia/Sydney",
        "FIJI" to "Pacific/Fiji",
        "PAPUA YENI GINE" to "Pacific/Port_Moresby",
        "GUAM ADASI" to "Pacific/Guam",
        "PALAU" to "Pacific/Palau",
        "TONGA" to "Pacific/Tongatapu",
        "SAMOA" to "Pacific/Apia",
        "VANUATU" to "Pacific/Efate",
        "YENI KALEDONYA" to "Pacific/Noumea",
        "TAHITI" to "Pacific/Tahiti",
        "HAWAII" to "Pacific/Honolulu",
    )

    /**
     * Returns the IANA zone id for a Diyanet country name, or null when unknown.
     */
    fun zoneIdForCountry(country: String): String? = map[country.trim().uppercase()]

    fun resolveTimezone(country: String): String {
        return zoneIdForCountry(country)
            ?.let { runCatching { ZoneId.of(it) }.getOrNull()?.id }
            ?: ZoneId.systemDefault().id
    }
}